### ISSUE TITLE
Upcoming Conference: DevConf.CZ 2022

### ISSUE THREAD

**Issue by isabelizimm** [AICoE/content-pipeline#10]
**Conference Name**
DevConf.CZ 2022
https://www.devconf.info/cz/

**Conference Date**
Jan 28-29, 2022

**Conference Location**
Brno, CZ and online

**CFP Opens**
CURRENTLY OPEN

**CFP Closes**
Oct 24

**Submission Link**
https://cfp.devconf.info/
Please link your DevConf.CZ 2022 proposals to this issue

**Comment by MichaelClifford** [comment]
https://github.com/AICoE/content-pipeline/issues/11 Was accepted.

**Comment by chauhankaranraj** [comment]
Uncovering Project Insights from GitHub PR Data (#29) was accepted.

**Comment by codificat** [comment]
Issue triage/party (#27) was accepted.

**Comment by hemajv** [comment]
Metrics All the Way: Data Driven DevOps (#24) was accepted

**Comment by MichaelClifford** [comment]
event over, closing
