### ISSUE TITLE
Conference talk: Project AI4CI 

### ISSUE THREAD

**Issue by oindrillac** [AICoE/content-pipeline#12]
**Overview**
Talk on AI4CI which is an intelligent open source AIOps toolkit which can be used to better monitor CI/CD workflows in order to help the development lifecycle.

**Speakers**
@oindrillac, @aakankshaduggal 

**What conference(s) are you submitting this proposal to?**
DevConf.US, Open Source Summit, Kubecon, Kubernetes AI Day @ Kubecon

**Project repo link, or other relevant resources**
https://github.com/aicoe-aiops/ocp-ci-analysis/tree/master/docs

**Link to abstract**

- [DevConf.US 21 Abstract](https://docs.google.com/document/d/1FPw1KzwStFS_nvth0OVlNvLZG57qeoBQsRHZGzxltMs/edit?usp=sharing)
- [Kubernetes AI Day 21 - Kubecon Abstract](https://docs.google.com/document/d/1RyPA24cOoN1EPrMUvXKFEdP-4a3R5Z0sTUPUJiQB-YU/edit?usp=sharing)
- [Open Source Summit 21 Abstract](https://docs.google.com/document/d/16aoBumBIB_7g3iEmClUAp5zCvz-6BORQvybd0rnH5_Y/edit?usp=sharing)

**Was this proposal accepted?**
- [x] Yes
- [ ] No

**Comment by isabelizimm** [comment]
Given at
- [X] DevConf.US 2021
- [X] KubeCon AI day
- [X] Open Source Summit

**Comment by oindrillac** [comment]
## DevConf.US 21
[Slides](https://static.sched.com/hosted_files/devconfus2021/9d/DevConf.US%20-%20AI4CI_Oindrilla_Aakanksha.pdf)
[Recording](https://www.youtube.com/watch?v=Zc25N1np59I)

## Open Source Summit 21
[Slides](https://static.sched.com/hosted_files/osselc21/d1/Open%20Source%20Summit%20-%20AI4CI.pdf)
[Recording](https://youtu.be/_RNCn-7oUjI)

## Kubernetes AI Day 21
[Slides](https://static.sched.com/hosted_files/kubernetesaidayna21/41/Kubernetes%20AI%20Day%20-%20AI4CI.pdf)
[Recording](https://www.youtube.com/watch?v=0-_RDgSGbe4)
