### ISSUE TITLE
KubeCon + CloudNativeCon 2022 - Spain

### ISSUE THREAD

**Issue by isabelizimm** [AICoE/content-pipeline#15]
**Conference Name**
KubeCon + CloudNativeCon

**Conference Date**
May 17-20, 2022

**Conference Location**
Valencia, Spain 

**CFP Opens**
Coming soon (normally open Oct-Jan)

**CFP Closes**
Coming soon (normally open Oct-Jan)

**Submission Link**
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/

**Comment by durandom** [comment]
duplicate of https://github.com/AICoE/content-pipeline/issues/42
