### ISSUE TITLE
Operate First: How to open source cloud operations

### ISSUE THREAD

**Issue by durandom** [AICoE/content-pipeline#17]
### Talk Abstract

Open source has become the defining way of developing software. 
But how do we open-source the operation of software? 

The Operate First Community Cloud is a peer-to-peer mentoring environment for running software in production, as well as a community for Cloud Native SREs to share knowledge about production practices.

Using the same community-building process of open source projects, but extended to ops procedures and data.

Did you ever want to peek into a data center?

See how Kubernetes, ArgoCD, Kubeflow, Prometheus and other workloads are deployed and operated including the real configs.
We’ll take you on a ride through the user-facing onboarding processes and the back office, where SRE’s perform state-of-the-art DevOps through GitOps and bot automation. 

Experienced SRE’s will find an outlet for sharing their knowledge and new talent get’s a chance to grow into an SRE role and get their hands on cloud-native projects in a production environment.

If you want to modernize your own environment, come and build on the community knowledge to get you bootstrapped.

**Speakers**

Marcel Hild

**What conference(s) are you submitting this proposal to?**

* Devconf.cz 2022 #10 

**Project repo link, or other relevant resources**

**Link to abstract**

https://docs.google.com/document/d/1t8KajPMjPdQrEaGWUkdMst8VNKtbQBr3QwvwGTMmmDQ/edit#heading=h.1dw18qfqm0fo

**Was this proposal accepted?**
- [ ] Yes
- [ ] No

**Comment by schwesig** [comment]
i think this can be closed?
devconf.cz 2022 is over and the talk/topics was presented as far as I know
