### ISSUE TITLE
Scale19x 2022 - CA

### ISSUE THREAD

**Issue by durandom** [AICoE/content-pipeline#20]
**Conference Name**
Scale19x

**Conference Date**
March 3-6, 2022 in 

**Conference Location**
Pasadena, CA. 

**CFP Opens**
20 Aug, 2021: CFP Opens

**CFP Closes**
30 Nov, 2021: Deadline for abstracts/proposals submissions

**Submission Link**
https://www.socallinuxexpo.org/scale/19x/cfp

**Comment by oindrillac** [comment]
More details:
A generalized community-owned public OSS conference, focused on
the Los Angeles community. This is a good event for first-time speakers. All content must
be 100% upstream.

Topics encouraged: anything open source

**Comment by quaid** [comment]
About the workshop idea:

The workshop is something we create and sponsor outside of the CFP deadline.

I've contacted SCaLE organizers and they're holding a slot for us for a workshop. These are often done on the first day of the conference before all the main tracks start, but we may be able to choose more (two-day, etc.) If we want anything beyond the space such as coffee and tea service, we will need to budget for that and arrange it directly with the event space (via our contacts at SCaLE).

We need to define what we want to do in that workshop. A couple of ideas I've thought of from recent discussions:

* UX testing
* Classroom with a bunch of laptops and hands-on GitOps activities
* Run some of the SRE curriculum; by March we should have a few early modules; course developers might want to do beta testing, for example.
* Demoing a cloud-native interactive learning platform

**Comment by quaid** [comment]
Regarding submitting papers:

A good practice is to coordinate across the project to avoid duplication, increase submission quality, and increase chances of talks getting accepted.

I understand the value in having a GitHub issue to track that discussion and decision. But it seems to me that only a few of us are aware of this issue and discussion? I'm going to put out a quick word on the mailing list and mention this issue as a central point, see if that helps increase visibility.

**Comment by HumairAK** [comment]
Agree with the curriculum suggestion, and the idea to send it out the mailing list, 
Would also be interested to know the main takeaways we want people to walk away with to help guide how we want to structure the workshop and what specifics we ought to cover.

**Comment by quaid** [comment]
> Agree with the curriculum suggestion, and the idea to send it out the mailing list, 

Done, thanks. We may create another parent issue to track things in the operate-first/community/ repo if this issue gets too full with cross-discussions. (I hope we get that much interest in submitting.)

> Would also be interested to know the main takeaways we want people to walk away with to help guide how we want to structure the workshop and what specifics we ought to cover.

Here is the strategic thinking:

1. KubeCon in Valencia is early May, then the Red Hat Summit to follow. These are excellent events for us to as "release" events, that is, to deliver a particular user experience by that event so we can talk about it, have presentations all center around it, etc.
2. It can (and should) be a lead in for us to KubeCon in Detroit in the Fall, build up expectation and interest. So we can choose what we deliver by May, and by October.
3. So then, SCaLE is our mid-way point to debut whatever parts of that experience are ready, and to get feedback and improve from there.

And that is why your question is super important. What is the Op1st user experience we want people to have?

**Comment by HumairAK** [comment]
I think we can start by identifying personas/user stories and have a workshop around that. We can also tie this in with discussions surrounding restructuring handbooks/docs and having starting paths for newcomers: 

Brainstorming some ideas: 
---

Persona: Software devs and devops engineers

Experience: software engineering, zero knowledge of k8s/ocp, maybe some knowledge about containers/github

Goal: Devops looking to deploying their software in an open cloud environment, having it managed via Git + ArgoCD, enabling monitoring for it, adding alerts (similar to the LF webinar, but further fine tuned/refined) 

---
Persona: Data scientist/engineer

Experience: ML / data driven tooling (notebooks, python, tensor flow, R, etc. etc.)  / object storage 

Goal: Getting access to ODH tools,  Performing data science example tasks on JH + Ceph -> Trino -> resulting in visualizing data on Superset on the operate-first cloud -- whilst using the publicly available data housed in our open bucket. 

@hemajv / @oindrillac / @aakankshaduggal can probably aid/tak part on this front as they are the most familiar with this sort of workflow 

---

Persona: SRE - monitoring focused 
Experience: familiarity with concept of logging, metrics, possibly promethius/grafana as well

Goal: Monitor your apps + cluster in an open fashion. Aggregating metrics/logs across clusters to a singular source and having it visualized by a single grafana instance. How to add new dashboards to the cloud. CLO -> Loki architecture. @4n4nd could help drive this as he's the mastermind behind this. 

---

I think that we decide should be incorporated into current discussions about adding learning paths as part of our documentations/guides/etc.
