### ISSUE TITLE
Uncovering Project Insights from GitHub PR Data

### ISSUE THREAD

**Issue by oindrillac** [AICoE/content-pipeline#29]
**Overview**
Uncovering Project Insights from GitHub PR Data

**Speakers**
@oindrillac @chauhankaranraj 

**What conference(s) are you submitting this proposal to?**
#10, #42

**Project repo link, or other relevant resources**
https://github.com/aicoe-aiops/ocp-ci-analysis

**Link to abstract**
https://cfp.devconf.info/proposals/37/3408

**Was this proposal accepted?**
- [x] Yes
- [ ] No

**Comment by chauhankaranraj** [comment]
Talk accepted to DevConf.CZ 2022 :tada:

**Comment by oindrillac** [comment]
Presented at #10 
[Youtube Video](https://youtu.be/bg-fZ7KGsbw) | [Slides](https://slides.com/chauhankaranraj/unconvering-insights-from-your-github)
