### ISSUE TITLE
Data Science Model Life Cycle Explained

### ISSUE THREAD

**Issue by hemajv** [AICoE/content-pipeline#31]
**Overview**
Connect with the women data scientists and software engineers at Red Hat who are leading the way on developing and designing Red Hat’s framework for managed services for use within the data science model life cycle. Within that framework, there are actually quite a few players/personas involved. We'll look at the people involved in this ML framework and the major stages of managed services that are required for model delivery. Each panelist will discuss and demo the basics of the stage of the data science life cycle that they are experts in and answer questions. Topics to be covered include: • Gathering/preparing data, • developing a ML model, • deploying a ML model with ML Ops Pipelines, and • monitoring and managing model performance. Along the way, we'll discuss various data services (Jupyter, Seldon Deploy, Starburst Galaxy) and highlight the importance of ML accelerators (NVIDIA GPUs) for the Red Hat OpenShift Data Science platform.

**Speakers**
Diane Mueller
@hemajv 
@isabelizimm 
@oindrillac 
@dfeddema 
@heyselbi 
@aakankshaduggal 

**What conference(s) are you submitting this proposal to?**
NVIDIA GTC (#30) , #51, #53 

**Project repo link, or other relevant resources**
NA

**Link to abstract**
https://docs.google.com/document/d/1xIl2U2oVgExnsBaI6GuMza6yphn-fP_7dkv_KHVB2Pk/edit?usp=sharing

**Was this proposal accepted?**
- [X] Yes
- [ ] No

**Comment by oindrillac** [comment]
Talk completed at #30 
On demand portal: https://reg.rainfocus.com/flow/nvidia/nvidiagtc/ap2/page/sessioncatalog/session/1631907700052001y2sB

**Comment by oindrillac** [comment]
Stats on the Nvidia session: SIMULIVE: A31663 - Data Science Model Life Cycle Explained had 197 total views (125 live) 💻

**Comment by oindrillac** [comment]
Summit Abstract: https://docs.google.com/document/d/1x4AH-d1jFuRcOxBRg9Eq3CcVnNS5ILb2M6zsTJQboFw/edit

**Comment by oindrillac** [comment]
Accepted at Red Hat Summit #53
