### ISSUE TITLE
Github Labeler

### ISSUE THREAD

**Issue by durandom** [AICoE/content-pipeline#33]
https://github.com/aicoe-aiops/github-labeler/issues/88

- [ ] create blog post out of video
- [ ] publish video to op1st YT

**Comment by antter** [comment]
@aakankshaduggal Should we close this issue?

**Comment by aakankshaduggal** [comment]
@antter we can close it out once we have Github Labeler on Operate First website.

**Comment by antter** [comment]
@aakankshaduggal Should we close now?
