### ISSUE TITLE
AIcoE Webcast

### ISSUE THREAD

**Issue by aakankshaduggal** [AICoE/content-pipeline#34]
## Topic
AICoE  Webcast

## Background
THe AICoE webcast allows contributors to present and showcase their work to the team. 

## Git artifacts, relevant resources
[Proposed Topics](https://docs.google.com/spreadsheets/d/1riykXedBshpwx0c9R0GzwktPo6UZo3_-uNE9pZW7qyY/edit#gid=0)
[Old Recordings](https://source.redhat.com/communitiesatredhat/communitiesofpractice/crosscuttingco/aicop/artificial_intelligencemachine_learning_community_of_practice_folder)

**Comment by schwesig** [comment]
rename it to OSG Webcast?
