### ISSUE TITLE
Kubecon EU 2022

### ISSUE THREAD

**Issue by oindrillac** [AICoE/content-pipeline#42]
**Conference Name**
Kubecon EU 2022

**Conference Date**
May 17-20, 2022

**Conference Location**
Valencia, Spain

**CFP Opens**
October 25, 2021

**CFP Closes**
Friday, December 17, 2021

**Submission Link**
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/cfp/

**Comment by oindrillac** [comment]
More details:

Proposals must be 100% upstream.  Additional opportunities include colocated events, office hours, booth demos, and more.

Topics encouraged: anything Cloud Native and open source

**Comment by MichaelClifford** [comment]
submitted #11

**Comment by tumido** [comment]
Submitted https://github.com/AICoE/content-pipeline/issues/48

**Comment by oindrillac** [comment]
submitted #29
