### ISSUE TITLE
Open Infrastructure Summit 2022

### ISSUE THREAD

**Issue by oindrillac** [AICoE/content-pipeline#44]
**Conference Name**
Open Infrastructure Summit 

**Conference Date**
June 7-9, 2022

**Conference Location**
Berlin Congress Center

**CFP Opens**
Open

**CFP Closes**
Feb 9, 2022

**Submission Link**
https://openinfra.dev/summit/

**Comment by oindrillac** [comment]
More details:

Open Infra Foundation's main event. Proposals should focus on Openstack, Katacontainers, and other
OpenInfra projects. Must be 100% upstream.

**Comment by MichaelClifford** [comment]
submitted #11
