### ISSUE TITLE
Create a google calendar to track conferences and CFP's?

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/content-pipeline#45]
It would be great if there was also a google calendar we could subscribe to that had all of the CFP openings and closings and conference dates. This would make it less likely any deadlines get missed.

**Comment by MichaelClifford** [comment]
cc @durandom @aakankshaduggal

**Comment by durandom** [comment]
/remove-lifecycle stale

cc @schwesig

**Comment by schwesig** [comment]
added to SP ComCom
https://github.com/orgs/open-services-group/projects/8/views/1?layout=board

**Comment by schwesig** [comment]
linked in https://github.com/orgs/open-services-group/projects/7/views/1
