### ISSUE TITLE
Cloud Native AI using Openshift (workshop)

### ISSUE THREAD

**Issue by pacospace** [AICoE/content-pipeline#48]
**Overview**
Cloud Native AI using Openshift

**Speakers**
@pacospace, @tumido @vpavlin 

**What conference(s) are you submitting this proposal to?**
DevConf CZ  2022, Brno

**Project repo link, or other relevant resources**
https://github.com/AICoE/elyra-aidevsecops-tutorial

**Link to abstract**
Ever thought of doing a cloud-native AI work? What does that even mean? This workshop will introduce you to running AI related services like Spark, Seldon or JupyterLab, Kubeflow Pipelines with Argo or Tekton on Kubernetes as part of Open Data Hub, how an open environment like Operate First can boost the development for all personas involved (e.g. data engineer, data scientists, developers) and how you can automate your tutorials using Project Meteor. You will learn how to move your AI workloads to the cluster and implement a basic data science workflow. We will show you how to use Jupyterlab and its extensions, interact with Kubeflow Pipelines and deploy an inference application adopting some of the best practices that we’ve developed over time.
This workshop will introduce participants to many of the open source projects available for AI services. In particular, how the Open Data Hub project running on Kubernetes brings benefits to the different personas (e.g. data engineer, data scientists, developers) involved in the development of an AI application.

**Was this proposal accepted?**
- [x] Yes
- [ ] No

**Comment by tumido** [comment]
Submitted to #42 with "DIY Cloud Native AI" title

**Comment by pacospace** [comment]
Delivered already!
