### ISSUE TITLE
Red Hat Summit 2022

### ISSUE THREAD

**Issue by oindrillac** [AICoE/content-pipeline#53]
**Conference Name**
Red Hat Summit 2022

**Conference Date**
Late Spring 2022

**Conference Location**
In-person/virtual TBD

**CFP Opens**
Open

**CFP Closes**
January 5, 2022

**Submission Link**
https://reg.experiences.redhat.com/flow/redhat/sum22/CFP/cfpHome

**Comment by MichaelClifford** [comment]
submitted #11 Data Science && Cloud Native Development == Awesome

**Comment by oindrillac** [comment]
submitted #54 Open Source AIOps powered by Elyra and Open Data Hub

**Comment by tumido** [comment]
Submitted https://github.com/AICoE/content-pipeline/issues/55

**Comment by oindrillac** [comment]
submitted #31
