### ISSUE TITLE
How to Make Your Python Jupyter Notebook Standalone and Reproducible to allow others to replicate your experiments

### ISSUE THREAD

**Issue by pacospace** [AICoE/content-pipeline#58]
**Overview**
How to Make Your Python Jupyter Notebook Standalone and Reproducible to allow others to replicate your experiments

**Speakers**
@pacospace @mayaCostantini 

**What conference(s) are you submitting this proposal to?**
https://github.com/AICoE/content-pipeline/issues/43

**Project repo link, or other relevant resources**
https://github.com/thoth-station/jupyterlab-requirements

**Link to abstract**
https://docs.google.com/document/d/13IO_6dozd_ykAY_qUConc7RIZgn5A_bNs-RlZazzowU/edit#

**Was this proposal accepted?**
- [x] Yes
- [ ] No

**Comment by mayaCostantini** [comment]
Update: proposal accepted

**Comment by mayaCostantini** [comment]
Closing this issue, see: https://www.youtube.com/watch?v=xJddVw_ALgY&ab_channel=PyConUS
/close
