### ISSUE TITLE
Write an article to offer a general overview of Thoth

### ISSUE THREAD

**Issue by mayaCostantini** [AICoE/content-pipeline#61]
## Project

Create an article on Red Hat Developers explaining project Thoth from a higher-level point of view and referring to all the content created so far about the project.

/assign @fridex 
/assign @mayaCostantini

**Comment by goern** [comment]
please think about publishing it on https://next.redhat.com/blog/ with a ton of links to developers.rh.c

**Comment by mayaCostantini** [comment]
Update: the article proposal was submitted for a publication on https://next.redhat.com/blog/

**Comment by mayaCostantini** [comment]
/close
See article: https://www.redhat.com/architect/manage-python-dependencies-thoth
