### ISSUE TITLE
AI4CI - Towards an open operations data community

### ISSUE THREAD

**Issue by aakankshaduggal** [AICoE/content-pipeline#64]
**Overview**
Applying AI to IT Operations(AIOps) is the thing of the hour. Most IT organizations generate a large amount of operations data in the process of operating their software and are beginning to embrace the adoption of AI to support IT operations. Yet, real world operations data is rarely available as a public dataset. Moreover, most AIOps tools out there are closed source.

In this session, the speakers introduce AI4CI(AI for Continuous Integration), a set of open source AIOps tools involving open operations data from Kubernetes CI/CD platforms. They demonstrate a set of Jupyter Notebooks that are automated using Kubeflow Pipelines into reproducible workflows that collect data from open CI/CD data sources, calculate and visualize key performance indicator metrics, and build AI/ML services to support operations.

By making the tools and relevant data openly accessible, AI4CI aims to cultivate an open source community that fosters collaboration between data scientists and DevOps engineers.

**Speakers**
@aakankshaduggal 
@oindrillac 

**What conference(s) are you submitting this proposal to?**
#51 #44 #22 

**Project repo link, or other relevant resources**
https://github.com/aicoe-aiops/ocp-ci-analysis

**Link to abstract**
https://docs.google.com/document/d/1TS1hMfAxbZ9jup6QMhqZB5DFfDnQafQmVW-uQb06UBE/edit?usp=sharing

**Was this proposal accepted?**
- [x] Yes
- [ ] No

**Comment by aakankshaduggal** [comment]
Accepted in #44

**Comment by oindrillac** [comment]
submitted #68 #66 #23
