### ISSUE TITLE
Open Source Summit North America 2022

### ISSUE THREAD

**Issue by aakankshaduggal** [AICoE/content-pipeline#66]
**Conference Name**
Open Source Summit North America 2022

**Conference Date**
June 21-24, 2022

**Conference Location**
Austin, TX

**CFP Opens**
Wednesday, January 19, 2022

**CFP Closes**
Monday, March 14, 2022 at 11:59 PM PST

**Submission Link**
https://linuxfoundation.smapply.io/prog/oss_na_2022/

**Comment by oindrillac** [comment]
Accepted #67

**Comment by hemajv** [comment]
Accepted #73
