### ISSUE TITLE
When To Stop: Optimize Test Runtimes Using AI4CI

### ISSUE THREAD

**Issue by aakankshaduggal** [AICoE/content-pipeline#72]
**Overview**
Longer running tests are often painful as they can block the CI/CD process for lengthy periods of time. How can we optimize the running time of our tests and prevent bottlenecks in our CI/CD pipeline? By understanding the test failure times, we aim to predict an Optimal Stopping Point for a test/build by training a machine learning model to help developers and managers better allocate the development resources, and ensure efficiency, consistency, and transparency for manual and time-consuming processes.

**Speakers**
@hemajv @aakankshaduggal 

**What conference(s) are you submitting this proposal to?**
#62 #23 

**Project repo link, or other relevant resources**
https://www.operate-first.cloud/data-science/ai4ci/docs/content.md#optimal-stopping-point-prediction

**Link to abstract**
https://cfp.devconf.info/proposals/40/3711

**Was this proposal accepted?**
- [ ] Yes
- [ ] No

**Comment by hemajv** [comment]
Submitted to #68

**Comment by hemajv** [comment]
Accepted in DevConf.US #62

**Comment by hemajv** [comment]
Submitted to #76
